export const ActionTypes = {
    SET_TOP_MOVIES:"SET_TOP_MOVIES",
    SET_ROMANCE_MOVIES:"SET_ROMANCE_MOVIES",
    SET_COMEDY_MOVIES:"SET_COMEDY_MOVIES",
    SET_SELECTED_MOVIE:"SET_SELECTED_MOVIE",
    DELETE_SELECTED_MOVIE:"DELETE_SELECTED_MOVIE",
    SET_RELATED_MOVIES:"SET_RELATED_MOVIES",
    SET_FOR_USER_MOVIES:"SET_FOR_USER_MOVIES",
    SET_WATCHED_MOVIES:"SET_WATCHED_MOVIES",
    USER_SIGNED_IN : "USER_SIGNED_IN",
    USER_SIGNED_OUT:"USER_SIGNED_OUT"

}